services:
  - type: web
    name: visaverse-faq-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GOOGLE_API_KEY
        sync: false  # Set this manually in the Render dashboard
